### ISSUE TITLE
review request

### ISSUE THREAD

**Issue by graysky2** [graysky2/kernel_compiler_patch#101]
@dargor @torvic9 @pfactum @sirlucjan - can I ask you guys to review a streamlined version of this work?  I am interested your feedback regarding applying AMD and INTEL specifics to entries in `arch/x86/Kconfig.cpu`, particularly:
* X86_L1_CACHE_SHIFT
*  X86_INTEL_USERCOPY
* X86_USE_PPRO_CHECKSUM
*  X86_P6_NOP
*  X86_HAVE_PAE
* X86_CMOV
*  X86_MINIMUM_CPU_FAMILY

Once verified, the "lite" patch can be integrated into the larger versions.

This is the lite patch to which I am refering: https://github.com/graysky2/kernel_compiler_patch/blob/master/lite-more-uarches-for-kernel-6.8-rc4%2B.patch

**Comment by ptr1337** [comment]
> The only difference between "v3" and "v4" is the addition of AVX512 instructions, which the kernel doesn't use anyway, so I'm not sure if it's worth including "v4".

Actually, the kernel does disable "avx" used in v3 also currently for the x86 Makefile:
https://github.com/torvalds/linux/blob/master/arch/x86/Makefile#L73

For rust avx2 got also disabled:
https://github.com/torvalds/linux/blob/master/arch/x86/Makefile#L75

So, i guess avx2, avx512 just got not disabled there so far.

**Comment by graysky2** [comment]
> EDIT: I'm stupid: the generic-v1/v2/v3/v4 are already x86_64, so IMO you can drop anything 32-bit related.

OK, so remove the modifications to the lines under `X86_TSC` and `X86_CMOV` as well as all lines modifying `vermagic.h`?

**Comment by graysky2** [comment]
> More generally though, does anyone have benchmark results especially for "v3" compared to "v1" (i.e. -march=x86-64)?

I have not done any benchmarking in quite some time.

**Comment by graysky2** [comment]
> More generally though, does anyone have benchmark results especially for "v3" compared to "v1" (i.e. -march=x86-64)?

Yes, I finally got around to running one this evening.  See the [README](https://github.com/graysky2/kernel_compiler_patch?tab=readme-ov-file#benchmarks) for the results.

**Comment by graysky2** [comment]
Thanks everyone for the time to review and for your thoughts
