### ISSUE TITLE
add -mno-tbm for MNATIVE_AMD

### ISSUE THREAD

**Issue by druggo** [graysky2/kernel_compiler_patch#104]
recently I compile the kernel with CONFIG_MNATIVE_AMD for FX8300 CPU and boot failed.

but it will boot with CONFIG_MPILEDRIVER, by getting help with [gentoo forum](https://forums.gentoo.org/viewtopic-t-1170957.html?sid=6a4a7d8ed3a140fa3704583fc0a5ee1e),
I found the difference is "-mno-tbm" was added ,

use native autodetect is more simple, can we have  "-mno-tbm" for MNATIVE_AMD ?

**Comment by thesamesam** [comment]
See also https://github.com/graysky2/kernel_compiler_patch/issues/55 and https://github.com/graysky2/kernel_compiler_patch/issues/80.

Really, all the `-mno-x` options should be added unconditionally unless we've seen a case where it causes some warning. Otherwise it's not going to be safe to use the native option in general.

**Comment by graysky2** [comment]
You're suggesting that `-mno-tbm` needs to be added to all AMD uarchs and to march=native for AMD?

**Comment by druggo** [comment]
> You're suggesting that `-mno-tbm` needs to be added to all AMD uarchs and to march=native for AMD?

add to march=native for AMD is fine

**Comment by graysky2** [comment]
> add to march=native for AMD is fine

1. Do any other AMD targets (eg MBOBCAT, etc.) need this too?
2. I do not build with rust but is the syntax the same, for example `rustflags-$(CONFIG_MNATIVE_AMD)         += -Ctarget-cpu=native -mno-tbm`?

**Comment by thesamesam** [comment]
> You're suggesting that -mno-tbm needs to be added to all AMD uarchs and to march=native for AMD? I know for a fact that for -march=znver3 it is not needed.

Not needed is not the same as it being harmful. There's no cost to adding the `-mno-x` other than cosmetics? There is cost to not adding it.

Besides, I don't see a way around it. native should always contain _all_ `-mno-x` you use in specific uarch configurations, because they're equivalent for some CPUs?

**Comment by graysky2** [comment]
Can you please check the closing commit.  Is this what you are recommending?

**Comment by druggo** [comment]
> > add to march=native for AMD is fine
> 
>     1. Do any other AMD targets (eg MBOBCAT, etc.) need this too?
> 
>     2. I do not build with rust but is the syntax the same, for example `rustflags-$(CONFIG_MNATIVE_AMD)         += -Ctarget-cpu=native -mno-tbm`?
To be honest, I'm not familiar with these.

> Can you please check the closing commit. Is this what you are recommending?

Yes, thanks!

PS, maybe this line was missed?
https://github.com/graysky2/kernel_compiler_patch/blob/master/more-ISA-levels-and-uarches-for-kernel-6.1.79-6.8-rc3.patch#L599

**Comment by graysky2** [comment]
I not not familiar either.  Yes, I missed one.  Fixed now.

**Comment by thesamesam** [comment]
That looks right to me, thanks.

**Comment by graysky2** [comment]
Can you list these options out for me? Save me some time of digging through the man page.

**Comment by thesamesam** [comment]
Sure, I'll get you a list later?

**Comment by graysky2** [comment]
Sure

**Comment by ptr1337** [comment]
> You're suggesting that `-mno-tbm` needs to be added to all AMD uarchs and to march=native for AMD? I know for a fact that for -march=znver3 it is not needed.

Neither needed on znver4 and znver5

**Comment by thesamesam** [comment]
The fact that it's not needed doesn't really mean much.

Again, the key point is that the compiler is free to generate whatever instructions the HW has if you pass these options. But we have two constraints:
1. We need to limit ourselves to instructions `objtool` can decode (and it can't handle tbm!)
2. We need to avoid vector instructions (e.g. https://github.com/graysky2/kernel_compiler_patch/issues/95)

Whether or not the compiler _happens to generate_ bad instructions doesn't matter, the point is it should be prevented from doing so in the first place via proper arguments.

Then in this instance, we had `-march=native` behaving differently from `-march=X` which is also wrong.

In terms of giving you a list, I don't actually know what you want -- you need to figure out a list of safe instructions and work from there. The rest is just gambling?

Like, for example, if you pass `-march=znver5`, what do you want the compiler to emit that _isn't_ a vector instruction and _is_ decodable by `objtool`?

**Comment by graysky2** [comment]
@druggo - can you verify that the latest commit builds and runs as expected?

**Comment by druggo** [comment]
> @druggo - can you verify that the latest commit builds and runs as expected?

yes, it's runs as expected!
