### ISSUE TITLE
MATOM/MCORE2 lines in lite patch

### ISSUE THREAD

**Issue by heftig** [graysky2/kernel_compiler_patch#105]
These lines should probably be removed:

```diff
+        cflags-$(CONFIG_MATOM) 	+= -march=bonnell
+        cflags-$(CONFIG_MCORE2) 	+= -march=core2
```

**Comment by heftig** [comment]
Also, the full patch should remove the original lines so that it doesn't produce two `march` arguments.

**Comment by heftig** [comment]
Also, `config SUPPORT_MARCH_CODEVERS` seems to be unused.

**Comment by heftig** [comment]
Also, the `MODULE_PROC_FAMILY` modifications seem to be incomplete. E.g., `ZEN5` is missing.

**Comment by heftig** [comment]
> Since these are valid uarches, why do you suggest removing them?

Because the patch leaves the original lines in place, creating two `-march` arguments:

```diff
         cflags-$(CONFIG_MCORE2)		+= -march=core2
         cflags-$(CONFIG_MATOM)		+= -march=atom
[…]
+        cflags-$(CONFIG_MATOM) 	+= -march=bonnell
+        cflags-$(CONFIG_MCORE2) 	+= -march=core2
```

And the lite patch, unlike the full one, does not have the `MINOR NOTES RELATING TO INTEL ATOM PROCESSORS`, so the added lines should be removed, not the original lines.

> Which original lines are you referencing?

The full patch has the same problem:

```diff
         cflags-$(CONFIG_MCORE2)		+= -march=core2
         cflags-$(CONFIG_MATOM)		+= -march=atom
[…]
+        cflags-$(CONFIG_MATOM) 	+= -march=bonnell
+        cflags-$(CONFIG_MCORE2) 	+= -march=core2
[…]
         rustflags-$(CONFIG_MCORE2)	+= -Ctarget-cpu=core2
         rustflags-$(CONFIG_MATOM)	+= -Ctarget-cpu=atom
[…]
+        rustflags-$(CONFIG_MATOM) 	+= -Ctarget-cpu=bonnell
+        rustflags-$(CONFIG_MCORE2) 	+= -Ctarget-cpu=core2
```

Here, the original lines should be removed.

> It is used when the user compiles with the `Generic-x86-64` Processor family selected. A value of `1` is the upstream default, but values of `2` or `3` switch to `-march=x86-64-v2` or `-march=x86-64-v3` respectively.

What do you mean? `config SUPPORT_MARCH_CODEVERS` is not used anywhere and you're talking about `config X86_64_VERSION`.

> My understanding about the entries in `arch/x86/include/asm/vermagic.h` is that they are used for 32-bit builds. I did not bother adding ZEN3+ here thinking that no one in their right mind with these CPUs would be building 32-bit kernels.

Fair enough.

**Comment by graysky2** [comment]
I see now, thank you for the suggestions.  Implemented in latest commit.
