### ISSUE TITLE
"AMD Zen 3" not available in "Processor family" in kernel config (menuconfig) with gcc-10.3.0

### ISSUE THREAD

**Issue by victor-vc** [graysky2/kernel_compiler_patch#75]
According to https://github.com/graysky2/kernel_compiler_patch/blob/master/more-uarches-for-kernel-5.8%2B.patch#L38 and https://github.com/graysky2/kernel_compiler_patch/blob/master/more-uarches-for-kernel-5.8%2B.patch#L61, the "AMD Zen 3" option (-march=znver3) requires GCC version >=10.3. However, https://github.com/graysky2/kernel_compiler_patch/blob/master/more-uarches-for-kernel-5.8%2B.patch#L222 states "depends on ( CC_IS_GCC && GCC_VERSION > 100300 )", so the kernel cannot be compiled for Zen 3 with GCC 10.3.

**Comment by pfactum** [comment]
My bad! 2eb521e9afdc34472594bf3a9eebe2130e09a126

@graysky2 shall you fix this directly, or I will submit a PR?

**Comment by graysky2** [comment]
Should be `>=` I believe, yes?  I can change it.

**Comment by graysky2** [comment]
Thanks for reporting.
