### ISSUE TITLE
Rebase against 5.15

### ISSUE THREAD

**Issue by barmadrid** [graysky2/kernel_compiler_patch#78]
Testing the new 5.15 rc1 kernel... the current patch cannot apply correctly.

```
patching file arch/x86/Kconfig.cpu
patching file arch/x86/Makefile
Hunk #1 FAILED at 114.
```
Thanks in advance!

**Comment by graysky2** [comment]
Thanks, some upstream changes.  I will apply a fix shortly.

**Comment by graysky2** [comment]
Please try it out

**Comment by barmadrid** [comment]
> Please try it out

Applied successfully. Thanks!

**Comment by barmadrid** [comment]
@graysky2 Applies against 5.15 fine. But fails with 5.13 and 5.14 using the renamed file `more-uarches-for-kernel-5.8-5.14.patch`

**Comment by graysky2** [comment]
Oops, I see what I did.  Just force pushed the fix.
