### ISSUE TITLE
It won’t boot, perhaps due to an illegal instruction

### ISSUE THREAD

**Issue by andrejpodzimek** [graysky2/kernel_compiler_patch#79]
Sorry for the clickbait title. Actually, it mostly boots and works perfectly fine, but AMD native optimizations (one of the last two options) don’t work for me for some reason. What works perfectly fine:

- Intel native optimizations (tried on 3 different Intel CPUs)
- AMD `-march=znver2` with Ryzen 3950X (mostly option `12`)

What doesn’t work (and hangs during boot without any log messages, soon after the initramdisk is loaded):

- This CPU
  ```
  vendor_id       : AuthenticAMD
  cpu family      : 23
  model           : 113
  model name      : AMD Ryzen 9 3950X 16-Core Processor
  stepping        : 0
  microcode       : 0x8701021
  ```
- AMD native / autodetected optimizations (one of the two last options)
- kernel `5.14.6` (last one I tried, but it hung with `5.14.2` too, so it might be really code-generation-related)
- GCC `11.1.0`
- ArchLinux with a [default kernel config](https://github.com/archlinux/svntogit-packages/blob/packages/linux/trunk/config) (with `kernel_compiler_patch` as the only tweak (before building `linux` with `makepkg`))
- Full hardware configuration [is listed here](https://bbs.archlinux.org/viewtopic.php?pid=1940994#p1940994) (in case it’s relevant); UEFI has been upgraded to `3.5` since that post.

Quite unfortunately I only have that^^^ one AMD machine, i.e. not many testing options. As noted earlier, **option 12 (`-march=znver2`) works perfectly fine**; it’s just the autodetection on AMD (**not** on Intel) that produces a bad kernel.

**Comment by andrejpodzimek** [comment]
Forgot to mention: When I build userspace stuff on the AMD machine with `-march=native`, it just works; I have never seen an unexpected crash or the like.

**Comment by sirlucjan** [comment]
@graysky2 Unfortunately I don't have AMD hardware to check this out. Perhaps we need to check if any flags have been missed?

**Comment by graysky2** [comment]
I am running a shiny new 5950X so I can test.  Not much free time to audit the patchset though.  Grateful if you can.

**Comment by barmadrid** [comment]
It works fine for me with `MNATIVE_AMD`. Tested against both `5.14.x` and `5.15-rc2 (mainline)` kernels
But I can test further if you wish. Just let me know what you're looking for in a test. Thanks.

**Comment by graysky2** [comment]
@andrejpodzimek - I cannot reproduce on my 5950X/B550 system.  Built 5.14.7 using Arch config (`make LSMOD=$HOME/.config/modprobed.db localmodconfig` to avoid building modules I don't use) with `MNATIVE_AMD` and have a bootable kernel.

**Comment by sirlucjan** [comment]
@graysky2 I checked the flags and I am 99.9% sure that everything is as it should be.

**Comment by graysky2** [comment]
OK, we have 2 people confirming correct behavior now.  I am not sure what to do with this issue...

**Comment by andrejpodzimek** [comment]
I’ll just keep selecting Zen2 (which works for me) instead of native then.

If the flags are OK, then it could be (e.g.) a compiler bug affecting the 3950X only (which sounds like it’s out-of-scope here).

Thanks a lot for double-checking it though. Maybe I should try and report it to GCC, but because the problem has an easy workaround, it’s probably not all that important.
