### ISSUE TITLE
mcpu-for-cortex

### ISSUE THREAD

**Issue by antonellocaroli** [graysky2/kernel_compiler_patch#81]
Hi,

do you think it is possible to patch rpi3 as well?

using:

`-mcpu=cortex-a52`

?

**Comment by graysky2** [comment]
For RPi4B: https://github.com/graysky2/kernel_compiler_patch/blob/master/build-with-mcpu-for-cortex-a72.patch which you can edit accordingly.  Pretty sure it's `-mcpu=cortex-a53` btw.

**Comment by graysky2** [comment]
Going to close this but feel free to keep a discussion active if needed.
