### ISSUE TITLE
Patch applies with fuzz 2 against 5.17 kernel

### ISSUE THREAD

**Issue by barmadrid** [graysky2/kernel_compiler_patch#82]
```
patching file arch/x86/Kconfig.cpu
Hunk #9 succeeded at 644 with fuzz 2.
```

**Comment by graysky2** [comment]
I think it's harmless, no?  Return code is 0.
```
% patch -Np1 -i ../more-uarches-for-kernel-5.15+.patch 
patching file arch/x86/Kconfig.cpu
Hunk #9 succeeded at 644 with fuzz 2.
Hunk #10 succeeded at 664 (offset -4 lines).
patching file arch/x86/Makefile
Hunk #1 succeeded at 131 (offset 12 lines).
patching file arch/x86/include/asm/vermagic.h
% echo $?
0
```

**Comment by barmadrid** [comment]
Not sure to be honest.
Can we create a new patch and re-base it against 5.17 tree just to be safe? Or is that too much work? Thanks!

**Comment by graysky2** [comment]
From what I read fuzz and offsets are fine when they don't result in an error.  That is the case here.  Can we create a new patch, yes, but I don't see the point in it.
