### ISSUE TITLE
Intel 9th gen CPU

### ISSUE THREAD

**Issue by STiNG645** [graysky2/kernel_compiler_patch#86]
What should I choose for an Intel 9th (Coffee Lake) generation processor? more precisely for i9 9900K?

**Comment by graysky2** [comment]
Model specific:
```
gcc -c -Q -march=native --help=target | grep march
```
Or generic level:
```
lib/ld-linux-x86-64.so.2 --help | grep supported
```

**Comment by STiNG645** [comment]
> Not totally sure... google? What does the following show?
> 
> ```
> gcc -c -Q -march=native --help=target | grep march
> ```

gcc -c -Q -march=native --help=target | grep march
  -march=                               skylake
  Known valid arguments for -march= option:

**Comment by graysky2** [comment]
There ya go.  You can also query which generic x86-64 version is supported if you want to go that route:
```
/lib/ld-linux-x86-64.so.2 --help | grep supported
```
