### ISSUE TITLE
path to ld-linux-x86-64.so.2

### ISSUE THREAD

**Issue by mid-kid** [graysky2/kernel_compiler_patch#91]
In the `more-uarches-for-kernel-5.17+.patch` file, the documentation suggests running `/lib/ld-linux-x86-64.so.2 --help | grep supported`. On my machine I had to change this to /lib64 instead of /lib.

**Comment by graysky2** [comment]
Yeah, Debian/Ubuntu put it there, thanks.
https://github.com/graysky2/kernel_compiler_patch/commit/759528e10fc7df6b778e7f242733ffd6a127e326

**Comment by mid-kid** [comment]
Everything uses /lib64, otherwise prebuilt binaries and things like AppImage wouldn't work :)
Thanks a lot!
