### ISSUE TITLE
more-uarches-for-kernel-6.1.79-6.8-rc3.patch patch failed on 6.7.5?

### ISSUE THREAD

**Issue by egnappahz** [graysky2/kernel_compiler_patch#94]
Hey eggz from the AUR here (linux-amd)

I'm either too tired too see what im missing (had a rough day) but as far as I see your patch

"more-uarches-for-kernel-6.1.79-6.8-rc3.patch" (from tag [20240221.2])

does not seem to be working on any of my 6.7.5 kernel builds with following error;

```bash
HEAD is now at 004dcea13dc1 Linux 6.7.5
git patches detected!!!
applying git patch ../more-uarches-for-kernel-6.1.79-6.8-rc3.patch
error: patch failed: arch/x86/Kconfig.cpu:356
error: arch/x86/Kconfig.cpu: patch does not apply
End of git patching!!!
```

while  "https://raw.githubusercontent.com/graysky2/kernel_compiler_patch/20230105/more-uarches-for-kernel-5.17+.patch still does work, which makes me doubt my exhaustion a little bit less.

Any idea whats going on here? That is the right patchfile for the current 6.7.5 linux right?

**Comment by sirlucjan** [comment]
It's patch for 6.1.79 and ### 6.6.17 and 6.7.6.

**Comment by egnappahz** [comment]
OK Thank you for clarification.

**Comment by graysky2** [comment]
Yeah, sorry... I was not clear what to use for naming to capture all the backports @sirlucjan called out.  Glad you got it squared away.
